development:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_development
  pool: 5
  username: postgres
  password:
